apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ctan
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0074-tenant/tkrw-pr712-0075-0074-app/devfile-sample-ctan@sha256:92c73adc76108d241f61a22de6b7cc2108b2a4b5e5d1bde87aa0f47e06abfd9c
        name: my-nodejs
        resources: {}
status: {}
